### ISSUE TITLE
wrong cross reference (non_block_corrals)

### ISSUE THREAD

**Issue by PuckiSilver** [HeDeAnTheonlyone/Taglib#14]
![commit message](https://user-images.githubusercontent.com/84644295/230787457-2838c29a-1cc8-4aa3-be95-4bdea09b8817.png)
You did rename the tag but in the `walk_through` tag, it still references the old one (`non_block_corrals`) instead

**Comment by HeDeAnTheonlyone** [comment]
I did change alk that but I forgot to upload
