### ISSUE TITLE
"Nether/End" version of "Overworld Natural"

### ISSUE THREAD

**Issue by Romaq** [HeDeAnTheonlyone/Taglib#18]
Create Mod is *CRAZY* for allowing me to set up #tag filters. I found your tag list looking for someone already wanting to fill out the Vanilla #tag list for this kind of use. Your wonderful datapack seriously fills that bill. I know I can temporarily make my own version of this datapack for my own specific need, you point the way.

However, I'm looking at your "overworld_natural.json" and wishing for "nether_natural.json" and "end_natural.json." I want to have a way to filter out netherack, nether plants, nether brick, magma blocks, and all those "boring/ quantity" blocks to get to the more interesting "chains, lanterns, drops" and such from structures, especially if I use mod packs that extend structures. I don't know what all of those might be, but I know what they are *NOT*: Natural Nether blocks.

Again, you point the way for me to make my own "add-on" for this, but if you willing to extend Taglib out to include the obvious, that would be a huge deal and may also prove useful to others.

Thank you.

**Comment by HeDeAnTheonlyone** [comment]
I planned to add them but I kinda forgot and also haven't had much time lately. I will add them maybe this week. Thanks for the praise and the reminder.

**Comment by Romaq** [comment]
Thank you for your prompt response! And yes, there is a *LOT* of territory to cover, so I understand if that were missed. AND you have new blocks coming with the 1.21 snapshots coming into view. I'm just happy someone else already did the work so I don't have to. Now if only we could get this built into Vanilla by Mojang? They're the ones *adding* the blocks and made #tagging possible. :) The Vanilla list just seems entirely too bare.

**Comment by HeDeAnTheonlyone** [comment]
Done, updated overworld natural block tag and added one for nether and end.
