### ISSUE TITLE
Add to Modrinth?

### ISSUE THREAD

**Issue by moxvallix** [HeDeAnTheonlyone/Taglib#9]
Modrinth is just adding a new datapack section, and I would love to see Taglib on there (it has better library support than PMC).

Hopefully you will consider adding it to Modrinth.

**Comment by HeDeAnTheonlyone** [comment]
I can upload it there too.

**Comment by HeDeAnTheonlyone** [comment]
Took like a wee for it to be reviewed but now it is on Modrinth too.
